export const USER_REPO_TOKEN = 'USER_REPO_TOKEN';
export const ROLE_REPO_TOKEN = 'ROLE_REPO_TOKEN';
export const PROFILE_REPO_TOKEN = 'PROFILE_REPO_TOKEN';
export const LEVEL_REPO_TOKEN = 'LEVEL_REPO_TOKEN';